### ISSUE TITLE
Kanban-board for Group Capstone(Ruby)

### ISSUE THREAD

**Issue by Daphineatim** [Daphineatim/catalog-of-my-things#32]
Hello reviewer 👋, 

Below is the link to our Ruby Capstone group project;
https://github.com/Daphineatim/catalog-of-my-things.git

We are three teammates and;
@Daphineatim is M1,
@svitalis123 is M2,
@Maxwell011 is M3. 

Thank you for reviewing our project.

**Comment by emmanuellekamwa** [comment]
**STATUS: APPROVED 🍾✔🎉**
Hello @Daphineatim, @svitalis123 and @Maxwell011 👋
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

- You documented your work professionally.✔

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Daphineatim** [comment]
Thank you for the approval.
